Refactoring for new version
wso2-extensions/siddhi-execution-kalmanfilter pull request #5
Opened 2017-06-16 12:46 UTC by Yasara123

2017-06-16 16:22 UTC, suhothayan requested changes

2017-06-16 16:22 UTC, suhothayan commented on component/pom.xml
> +            <version>4.0.0-SNAPSHOT</version>
You should not use versions here! they should always be in the parent poms properties section

2017-06-16 18:11 UTC, Yasara123 commented on component/pom.xml
> +            <version>4.0.0-SNAPSHOT</version>
Fixed in  	88a0085

2017-06-18 05:24 UTC, suhothayan approved these changes

2017-06-18 05:24 UTC, merged